std_type_dir=./std_type
labs_src=./labs/labs.c
main_src=./main/main.c

library.exe: $(main_src) $(labs_src)
	@gcc $(main_src) $(labs_src) -o library.exe
	@echo "*********** library is generated ***********"